# Generated by Django 4.0.6 on 2022-07-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=20)),
                ('weight_feed', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
